# Generated by Django 3.2.5 on 2022-09-10 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_scholar', models.URLField(max_length=150)),
                ('research_gate', models.URLField(max_length=150)),
                ('status', models.CharField(choices=[('P', 'pending'), ('D', 'declined'), ('A', 'approved')], default='P', max_length=2)),
                ('applied_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.CharField(blank=True, max_length=150)),
                ('content_post_id', models.CharField(blank=True, max_length=150)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='phisuser',
            name='auth_user_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phisuser',
            name='user_role',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
