# Generated by Django 4.0 on 2022-12-01 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_scholar', models.URLField(null=True, unique=True)),
                ('research_gate', models.URLField(null=True, unique=True)),
                ('scopus', models.URLField(null=True, unique=True)),
                ('pub_med', models.URLField(null=True, unique=True)),
                ('capic_status', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('P', 'pending'), ('D', 'declined'), ('A', 'approved')], default='P', max_length=2)),
                ('applied_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('number_followers', models.IntegerField(default=0)),
                ('followers_data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.CharField(blank=True, max_length=150)),
                ('content_post_id', models.CharField(blank=True, max_length=150)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menucreated']},
        ),
        migrations.AlterModelOptions(
            name='microservice',
            options={'ordering': ['microserviceCreated']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='phisuser',
            name='auth_user_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='phisuser',
            name='following_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='phisuser',
            name='user_role',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menustatus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPHIS.phisuser'),
        ),
        migrations.AlterField(
            model_name='phisuser',
            name='about',
            field=models.TextField(blank=True, max_length=1000, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenustatus',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=200)),
                ('roleshortname', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=400)),
                ('rolestatus', models.CharField(max_length=200)),
                ('roledescription', models.CharField(max_length=400)),
                ('roleupdated', models.DateTimeField(auto_now=True)),
                ('rolecreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPHIS.phisuser')),
            ],
            options={
                'ordering': ['rolecreated'],
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, unique=True)),
                ('number_followers', models.IntegerField(default=0)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submenu',
            name='role',
            field=models.ManyToManyField(to='adminPHIS.Role'),
        ),
    ]
