# Generated by Django 4.1.3 on 2023-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminPHIS", "0002_authorapplication_post_alter_menu_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="unique_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
