# Generated by Django 3.2.5 on 2022-09-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0002_auto_20220910_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='google_scholar',
            field=models.URLField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='research_gate',
            field=models.URLField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
