# Generated by Django 4.1.1 on 2022-10-25 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0002_auto_20220910_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorapplication',
            name='capic_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='number_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='pub_med',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='scopus',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='google_scholar',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='research_gate',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='phisuser',
            name='user_role',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, unique=True)),
                ('number_followers', models.IntegerField(default=0)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]