# Generated by Django 4.0 on 2024-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0003_role_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='phisuser',
            name='profile_picture',
            field=models.CharField(default='/media/profiles/default.png', max_length=250),
        ),
    ]
