# Generated by Django 4.1.1 on 2022-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0003_authorapplication_capic_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorapplication',
            name='followers',
        ),
        migrations.AddField(
            model_name='authorapplication',
            name='followers_data',
            field=models.JSONField(null=True),
        ),
    ]