# Generated by Django 4.1.1 on 2022-11-14 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0004_remove_authorapplication_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phisuser',
            name='following_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phisuser',
            name='about',
            field=models.TextField(blank=True, max_length=1000, verbose_name='about'),
        ),
    ]